org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom_version=1.10-SNAPSHOT
loom.platform=neoforge

group = team.cagayakegirls
mod_id = mafglib
mod_name = MaFgLib
author = masa
mod_file_name = mafglib
mod_link = https://github.com/CagayakeGirls/malilib-neoforge

fml_version_range = [4,)
minecraft_version_range = [1.21.6,)
neoforge_version_range = [21.6,)

# Current mod version
mod_version = 0.4.0
version_type = alpha

# Minecraft, NeoForge and mappings versions
minecraft_version_out = 1.21.8
minecraft_version = 1.21.8
mappings_version = 1.21.8+build.1

neoforge_version = 21.8.4-beta
iris_version = 1.9.1
iris_mc_version = 1.21.7
fabric_api_version = 0.129.0+2.0.26+1.21.8

curseforge_id = SKI34J7B
modrinth_id = 910766
