org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = mafglib
mod_name = MaFgLib
author = masa
mod_file_name = mafglib

# Current mod version
mod_version = 0.6.0

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.3
minecraft_version = 26.3

neoforge_version = 26.3.0.26-beta
foxified_classtweaker_version = 0.1.0-alpha.4

sodium_version = 0.9.2
sodium_mc_version = 26.3
iris_version = 1.11.6
iris_mc_version = 26.3
conditionalmixin_version = 0.6.4
