org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = mafglib
mod_name = MaFgLib
author = masa
mod_file_name = mafglib
mod_link = https://github.com/CagayakeGirls/malilib-neoforge

fml_version_range = [4,)
minecraft_version_range = [1.21.3,)
neoforge_version_range = [21.3,)

# Current mod version
mod_version = 0.4.2
version_type = release

# Minecraft, NeoForge and mappings versions
minecraft_version_out = 1.21.4
minecraft_version = 1.21.4
mappings_version = 1.21.4+build.8

neoforge_version = 21.4.156
fabric_api_version = 0.107.0+2.0.26+1.21.4

curseforge_id = 910766
modrinth_id = SKI34J7B
