[versions]
range-fml = "[4,)"
range-game = "[1.21.9,)"
range-neoforge = "[21.9,)"

mod-link = "https://github.com/CagayakeGirls/malilib-neoforge"

version-env = "client"
version-type = "release"

platformId-curseforge = "910766"
platformId-modrinth = "SKI34J7B"

yarn-patch = "1.21+build.4"

koom = "1.13-SNAPSHOT"
modpublisher = "2.+"

[libraries]
yarn-patch = { group = "dev.architectury", name = "yarn-mappings-patch-neoforge", version.ref = "yarn-patch" }

[plugins]
koom = { id = "band.kessoku.koom", version.ref = "koom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }